name: privacy_policy_plus
version: 1.2.0
homepage: https://github.com/changyy/privacy_policy_plus_dart
description: >
  A Flutter package to quickly display a customizable privacy policy page with hierarchical structure, multi-language support, region logic, and version control.
license: MIT
environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.15
flutter:
  uses-material-design: true
